import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const firaMono = localFont({
  src: "./fonts/FiraMono.woff2",
  variable: "--font-fira-mono",
  weight: "100 900"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={firaMono.className}>
        {children}
      </body>
    </html>
  );
}
